version: '3'  
services:
  event-service:
    image: docerfnc/ticketbooking-a-buildkite-test:latest
    ports:
      - "8080:8080"
  app:
    build: ./event-backend
    depends_on:
      - event-service
