  - input: "pre-checkout the modified US"
    fields:
      - text: "US Number:"
        key: "us"
        hint: "Please enter the ID numbers of the modified user stories that require validation, separated by commas. For example: 1,3,5."
        format: "[0-9,]+"
