env:
  BUILDKITE_HOOKS_PATH: .
  PROPERTY_ONE: "admin@email.com" #username
  PROPERTY_TWO: "admin" #password
  
steps: 
  # - label: "Run FE"
  #   command: 
  #     - sleep 15
  #     - cd event-app && npm install && npm run build
  #     - npm install -g serve
  #     - serve -s build -l 3000
  #     # - sleep 10 # Waits for 10 seconds to ensure the server has started
  #     # - curl --fail http://localhost:3000
  #   agents:
  #     queue: fe

  # - label: “Forward to backend folder”
  #   command: cd event-backend

  # - label: "Docker Test" 
  #   plugins:
  #     - docker-login:
  #         username: docerfnc
  #     # Resolves to https://github.com/my-org/docker-buildkite-plugin
  #     - docker-compose#v4.16.0:
  #         # build: app
  #         # image-repository: docerfnc/ticketbooking-a-buildkite-test
  #         run: app


  - label: ":book: User story validation"
    key: us-validation
    plugins:
<<<<<<< HEAD
      - git@github.com:MotivationalModelling/buildkite-plugin-user-story-validator.git:
      #  - https://github.com/yuesong1/BKPlugin.git:
          propertyone: checkProp1
	        user-stories-dir: ./user-stories
=======
      - ssh://git@github.com/MotivationalModelling/buildkite-plugin-user-story-validator.git:
        # - ssh://git@github.com:TBPlatform/validator.git#v0.0.1:
          propertyone: $PROPERTY_ONE
          user-stories-json-directory: ./
>>>>>>> cfbac968d5bb839ab64bb7cbd80ac1db8c8c36b6
          
  # - label: ":point_up::skin-tone-3: 'Pre-command' to check format"
  #   command: chmod +x pre-command.sh && ./pre-command.sh

  # - label: ":v::skin-tone-3: 'Command' to generate result"
  #   command: chmod +x command.sh && ./command.sh

  # - label: "Extra annotation Test"
  #   command:
  #     - echo -e "\`\`\`term\nThis is a \033[0;31mtest\033[0m\n\`\`\`" | buildkite-agent annotate
      
