env:
  BUILDKITE_HOOKS_PATH: .
  PROPERTY_ONE: "user-stories.json" #username
  PROPERTY_TWO: "user-stories.json" #password
  # PROPERTY_THREE: "three"
steps: 
  - label: ":book: User story validation"
    agents:
      queue: outer
    key: us-validation
    plugins:
      - ssh://git@github.com/MotivationalModelling/buildkite-plugin-user-story-validator.git:
        # - ssh://git@github.com:TBPlatform/validator.git#v0.0.1:
          propertyone: $PROPERTY_ONE
          propertytwo: $PROPERTY_TWO
          # propertythree: $PROPERTY_THREE
          
  - label: ":point_up::skin-tone-3: 'Pre-command' to check format"
    command: chmod +x pre-command.sh && ./pre-command.sh
    
  - input: "pre-checkout the modified US"
    fields:
      - text: "US Number:"
        key: "us"
  - label: "Pre-checkout script"
    command: pre-checkout.sh

  - label: ":v::skin-tone-3: 'Command' to generate result"
    command: chmod +x command.sh && ./command.sh



      
