steps:
  - label: ":node:start the frontend"
    command:
      - "cd event-app"
      - "npm install && npm start"
    # Wait for the web application to start (you may need to adjust the URL)
    wait: "http://localhost:3000"
    continue_on_failure: true # Continue the build even if the check fails
    branches: "*"

  - label: ":check: Web Application Check"
    depends_on: ":node:start the frontend"
    command:
      - "curl -IsS http://localhost:3000 | grep '200 OK'"
    agents:
      queue: "default"
    branches: "*"
