env:
  BUILDKITE_HOOKS_PATH: .
  PROPERTY_ONE: "USER" # Mode config
  # PROPERTY_TWO: "1,2,3" # IDs for testing
  # PROPERTY_THREE: "three"
agents:
  queue: local
steps: 
  - label: ":v::skin-tone-3:"
    command: buildkite-agent pipeline upload input.yaml
    
  - label: ":book: User story validation"
    agents:
      queue: outer
    key: us-validation
    plugins:
      - ssh://git@github.com/MotivationalModelling/buildkite-plugin-user-story-validator.git:
        # - ssh://git@github.com:TBPlatform/validator.git#v0.0.1:
          user-stories-dir: ./
          propertyone: $PROPERTY_ONE
          # propertytwo: $PROPERTY_TWO
          # propertythree: $PROPERTY_THREE
          
  # - label: ":point_up::skin-tone-3: 'Pre-command' to check format"
  #   command: chmod +x pre-command.sh && ./pre-command.sh
    
  # - input: "pre-checkout the modified US"
  #   fields:
  #     - text: "US Number:"
  #       key: "us"
  #       hint: "Please enter the ID numbers of the modified user stories that require validation, separated by commas. For example: 1,3,5."
  #       format: "[0-9,]+"
  
  # - label: ":v::skin-tone-3: Checkout and Command"
  #   command: ./pre-checkout.sh && ./command.sh
  #            # chmod +x command.sh && ./command.sh

  # - label: ":v::skin-tone-3: 'Command' to generate result"
  #   command: chmod +x command.sh && ./command.sh



      
