steps:
  - label: “:package: Forward to backend folder”
    command: "cd event-backend"

  - wait

  - label: ":docker: Docker Test"
    command: “ “     
    plugins:
      - docker-compose#v3.0.3:
        run: app
