env:
  BUILDKITE_HOOKS_PATH: .
steps:
  - label: “Forward to backend folder”
    command: cd event-backend

  - label: "Build FE"
    command: cd event-app && npm install && npm run build  
    
  - label: "Run FE"
    command: 
      # - npm install -g serve
      - serve -s build -l 3000
      - sleep 10 # Waits for 5 seconds to ensure the server has started
      - curl --fail http://localhost:3000
  
  - label: "Docker Test" 
    plugins:
      - docker-login:
          username: docerfnc
      # Resolves to https://github.com/my-org/docker-buildkite-plugin
      - docker-compose#v4.16.0:
          # build: app
          # image-repository: docerfnc/ticketbooking-a-buildkite-test
          run: app
          
  # - label: "Docker Run" 
  #   plugins:
  #     - docker-login:
  #         username: docerfnc
      
  #     # Resolves to https://github.com/my-org/docker-buildkite-plugin
  #     - docker-compose#v4.16.0:
  #         run: app
