env:
  BUILDKITE_HOOKS_PATH: .
  VALIDATION_MODE: "INT" # Mode config
  PROPERTY_TWO: "" # IDs for testing
  # PROPERTY_THREE: "three"
agents:
  queue: local
steps: 
  - label: 👀
    command: buildkite-agent annotate --style 'info'
    default: |
          <h4>VENUS Feedback</h4>
          <dl class="flex flex-wrap mxn1">
            <div class="m1">
              <dt>New Files in PR</dt>
              <dd>
                <big><big>88</big></big>%<br>
                115 of 131 lines<br>
              </dd>
            </div>
            <div class="m1">
              <dt>Files Changed in PR</dt>
              <dd>
                <big><big>89</big></big>%<br>
                332 of 372 lines
              </dd>
            </div>
            <div class="m1">
              <dt>All Files</dt>
              <dd>
                <big><big>90</big></big>%<br>
                22,998 of 25,484 lines
              </dd>
            </div>
          </dl>
          <h4>User Story Validation</h4>
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>Score(Required Score)</th>
                <th>Risk/Problem</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>baz</td>
                <td>bim</td>
                <td>xx</td>
              </tr>
            </tbody>
          </table>

  - label: ":book: User story validation"
    key: us-validation
    plugins:
      - ssh://git@github.com/MotivationalModelling/buildkite-plugin-user-story-validator.git:
        # - ssh://git@github.com:TBPlatform/validator.git#v0.0.1:
          user-stories-dir: ./
          validation-mode: $VALIDATION_MODE
          propertytwo: $PROPERTY_TWO
          # propertythree: $PROPERTY_THREE
  # depends_on: "block"
          
  # - label: ":point_up::skin-tone-3: 'Pre-command' to check format"
  #   command: chmod +x pre-command.sh && ./pre-command.sh
    
  # - input: "pre-checkout the modified US"
  #   fields:
  #     - text: "US Number:"
  #       key: "us"
  #       hint: "Please enter the ID numbers of the modified user stories that require validation, separated by commas. For example: 1,3,5."
  #       format: "[0-9,]+"
  
  # - label: ":v::skin-tone-3: Checkout and Command"
  #   command: ./pre-checkout.sh && ./command.sh
  #            # chmod +x command.sh && ./command.sh

  # - label: ":v::skin-tone-3: 'Command' to generate result"
  #   command: chmod +x command.sh && ./command.sh



      
