env:
  BUILDKITE_HOOKS_PATH: .
  PROPERTY_ONE: "admin@email.com" #username
  PROPERTY_TWO: "admin" #password
  # PROPERTY_THREE: "three"
steps: 
  - label: "Run FE"
    command: 
      - sleep 15
      - cd event-app && npm install && npm run build
      - npm install -g serve
      - serve -s build -l 3000
      # - sleep 10 # Waits for 10 seconds to ensure the server has started
      # - curl --fail http://localhost:3000
    agents:
      queue: fe

  - label: “Forward to backend folder”
    command: cd event-backend
          
  - label: "Docker Test" 
    plugins:
      - docker-login:
          username: docerfnc
      # Resolves to https://github.com/my-org/docker-buildkite-plugin
      - docker-compose#v4.16.0:
          build: app
          image-repository: docerfnc/ticketbooking-a-buildkite-test:initial-deployment-app-build-72
          run: app

  - label: ":book: User story validation"
    agents:
      queue: outer
    key: us-validation
    plugins:
      - ssh://git@github.com/MotivationalModelling/buildkite-plugin-user-story-validator.git#v0.0.1:
          propertyone: $PROPERTY_ONE
          propertytwo: $PROPERTY_TWO
          # propertythree: $PROPERTY_THREE

