env:
  BUILDKITE_HOOKS_PATH: .
steps:
  - label: “Forward to backend folder”
    command: cd event-backend

  - label: "Run FE"
    command: cd event-app && npm install && npm run build
  
  - label: "Docker Test" 
    plugins:
      - docker-login:
          username: docerfnc
      # Resolves to https://github.com/my-org/docker-buildkite-plugin
      - docker-compose#v4.16.0:
          # build: app
          # image-repository: docerfnc/ticketbooking-a-buildkite-test
          run: app
          
  # - label: "Docker Run" 
  #   plugins:
  #     - docker-login:
  #         username: docerfnc
      
  #     # Resolves to https://github.com/my-org/docker-buildkite-plugin
  #     - docker-compose#v4.16.0:
  #         run: app
