steps:
  - label: ":node:start the frontend"
    command: "cd event-app && npm install && npm start"
  - wait

  - label: ":check: Web Application Check"
    command:
      - "curl -IsS http://localhost:3000 | grep '200 OK'"
